/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.jayanidu.gui;

import com.jayanidu.model.MySQL;
import com.jayanidu.model.TableAlignment;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class Branch extends javax.swing.JDialog {

    /**
     * Creates new form Branch
     */
    public Branch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadCompanies();
        loadCities();
        loadTable();
    }

    SalesRep sr;

    public Branch(SalesRep parent, boolean modal) {
        super(parent, modal);

        this.sr = parent;

        initComponents();

        jTable1.getColumnModel().getColumn(0).setCellRenderer(TableAlignment.centerAlignment());
        jTable1.getColumnModel().getColumn(1).setCellRenderer(TableAlignment.centerAlignment());
        jTable1.getColumnModel().getColumn(2).setCellRenderer(TableAlignment.centerAlignment());
        jTable1.getColumnModel().getColumn(3).setCellRenderer(TableAlignment.centerAlignment());
        jTable1.getColumnModel().getColumn(4).setCellRenderer(TableAlignment.centerAlignment());

        loadCompanies();
        loadCities();
        loadTable();

        setLocationRelativeTo(sr);
    }

    public void loadCompanies() {
        try {

            ResultSet rs = MySQL.search("SELECT * FROM `company` WHERE `status` = 1 ORDER BY `name` ASC");
            Vector v = new Vector();
            v.add("Select Company");
            while (rs.next()) {
                v.add(rs.getString("name"));
            }

            DefaultComboBoxModel cbm = new DefaultComboBoxModel(v);
            jComboBox1.setModel(cbm);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadCities() {
        try {

            ResultSet rs = MySQL.search("SELECT * FROM `city` WHERE `status` = 1 ORDER BY `name` ASC");
            Vector v = new Vector();
            v.add("Select City");
            while (rs.next()) {
                v.add(rs.getString("name"));
            }

            DefaultComboBoxModel cbm = new DefaultComboBoxModel(v);
            jComboBox3.setModel(cbm);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadTable() {
        try {

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = MySQL.search("SELECT * FROM `branch` INNER JOIN `company` ON `branch`.`company_id` = `company`.`id` INNER JOIN `city` ON `branch`.`city_id` = `city`.`id` WHERE `branch`.`status` = 1 ORDER BY `company`.`name` ASC");

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("company.name"));
                v.add(rs.getString("branch.name"));
                v.add(rs.getString("branch.phone"));
                v.add(rs.getString("branch.line1") + " " + rs.getString("branch.line2"));
                v.add(rs.getString("city.name"));
                dtm.addRow(v);
            }

            jTable1.setModel(dtm);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearFields() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        jMenuItem1.setText("Remove Branch");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Ravie", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 30, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("BRANCH");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 530, 70));
        jLabel8.setBackground(new Color(242, 242, 242, 120));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 178, 194), 3));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 73, 94));
        jLabel1.setText("Company Name");

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(52, 73, 94));

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(52, 73, 94));
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 73, 94));
        jLabel2.setText("Branch Name");

        jTextField1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(52, 73, 94));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 73, 94));
        jLabel3.setText("Address Line 1");

        jTextField2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(52, 73, 94));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 73, 94));
        jLabel4.setText("Address Line 2");

        jTextField3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(52, 73, 94));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 73, 94));
        jLabel5.setText("Contact Number");

        jTextField4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(52, 73, 94));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 73, 94));
        jLabel6.setText("City");

        jComboBox3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(52, 73, 94));

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(52, 73, 94));
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(52, 73, 94));
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(52, 73, 94));
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(52, 73, 94));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company", "Branch", "Contact Number", "Address ", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 104, -1, 420));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jayanidu/resources/29.jpg"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 178, 194), 5));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Company(this, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new AddCity(this, true).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String cname = jComboBox1.getSelectedItem().toString();
        String bname = jTextField1.getText().trim();
        String l1 = jTextField2.getText().trim();
        String l2 = jTextField3.getText().trim();
        String cnum = jTextField4.getText().trim();
        String city = jComboBox3.getSelectedItem().toString();

        if (cname.equals("Select Company")) {
            JOptionPane.showMessageDialog(this, "Please select a company!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (bname.isBlank()) {
            JOptionPane.showMessageDialog(this, "Branch Name field empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (bname.length() > 45) {
            JOptionPane.showMessageDialog(this, "Branch Name field out of range!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (l1.isBlank()) {
            JOptionPane.showMessageDialog(this, "Address Line 1 field empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (l1.length() > 45) {
            JOptionPane.showMessageDialog(this, "Address Line 1 field out of range!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (l2.isBlank()) {
            JOptionPane.showMessageDialog(this, "Address Line 2 field empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (l2.length() > 45) {
            JOptionPane.showMessageDialog(this, "Address Line 2 field out of range!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (cnum.isBlank()) {
            JOptionPane.showMessageDialog(this, "Contact Number field empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (cnum.length() > 45) {
            JOptionPane.showMessageDialog(this, "Contact Number field out of range!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (city.equals("Select City")) {
            JOptionPane.showMessageDialog(this, "Please select a city!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {

                ResultSet rs = MySQL.search("SELECT * FROM `branch` INNER JOIN `company` ON `branch`.`company_id` = `company`.`id` WHERE `branch`.`name` = '" + bname + "' AND `company`.`name` = '" + cname + "' AND `branch`.`status` = 1 AND `company`.`status` = 1");
                if (!rs.next()) {
                    ResultSet rs1 = MySQL.search("SELECT * FROM `company` WHERE `name` = '" + cname + "'");
                    ResultSet rs2 = MySQL.search("SELECT * FROM `city` WHERE `name` = '" + city + "'");
                    rs1.next();
                    rs2.next();

                    MySQL.iud("INSERT INTO `branch`(`company_id`,`name`,`phone`,`line1`,`line2`,`city_id`) VALUES(" + rs1.getInt("id") + ",'" + bname + "','" + cnum + "','" + l1 + "','" + l2 + "'," + rs2.getInt("id") + ")");
                    JOptionPane.showMessageDialog(this, "Branch added successfull!", "Success", JOptionPane.INFORMATION_MESSAGE);

                    clearFields();
                    loadTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Branch already exists!", "Warning", JOptionPane.WARNING_MESSAGE);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    int clickedId;
    String clickedCname;
    String clickedBname;
    String clickedCnum;
    String clickedL1;
    String clickedL2;
    String clickedCity;

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 1) {
            int row = jTable1.getSelectedRow();

            if (row != -1) {
                try {

                    ResultSet rs = MySQL.search("SELECT * FROM `branch` INNER JOIN `company` ON `branch`.`company_id`  = `company`.`id` WHERE `branch`.`name` = '" + jTable1.getValueAt(row, 1).toString() + "' AND `company`.`name` = '" + jTable1.getValueAt(row, 0).toString() + "'");
                    rs.next();
                    clickedId = rs.getInt("branch.id");
                    clickedBname = rs.getString("branch.name");
                    clickedCnum = rs.getString("branch.phone");
                    clickedL1 = rs.getString("branch.line1");
                    clickedL2 = rs.getString("branch.line2");
                    jTextField1.setText(clickedBname);
                    jTextField2.setText(clickedL1);
                    jTextField3.setText(clickedL2);
                    jTextField4.setText(clickedCnum);

                    ResultSet rs1 = MySQL.search("SELECT * FROM `company` WHERE `id` = " + rs.getInt("branch.company_id") + "");
                    ResultSet rs2 = MySQL.search("SELECT * FROM `city` WHERE `id` = " + rs.getInt("branch.city_id") + "");
                    rs1.next();
                    rs2.next();

                    Vector v1 = new Vector();
                    clickedCname = rs1.getString("name");
                    v1.add(clickedCname);
                    ResultSet rs3 = MySQL.search("SELECT * FROM `company` WHERE `name` <> '" + clickedCname + "' AND `status` = 1 ORDER BY `name` ASC");
                    while (rs3.next()) {
                        v1.add(rs3.getString("name"));
                    }

                    DefaultComboBoxModel cbm1 = new DefaultComboBoxModel(v1);
                    jComboBox1.setModel(cbm1);

                    Vector v2 = new Vector();
                    clickedCity = rs2.getString("name");
                    v2.add(clickedCity);
                    ResultSet rs4 = MySQL.search("SELECT * FROM `city` WHERE `name` <> '" + clickedCity + "' AND `status` = 1 ORDER BY `name` ASC");
                    while (rs4.next()) {
                        v2.add(rs4.getString("name"));
                    }

                    DefaultComboBoxModel cbm2 = new DefaultComboBoxModel(v2);
                    jComboBox3.setModel(cbm2);

                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        }

        if (evt.getClickCount() == 2) {
            int row = jTable1.getSelectedRow();

            if (row != -1) {
                if (sr != null) {
                    sr.jTextField6.setText(clickedCname);
                    sr.jTextField5.setText(clickedBname);
                    sr.branchId = clickedId;
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        String cname = jComboBox1.getSelectedItem().toString();
        String bname = jTextField1.getText().trim();
        String l1 = jTextField2.getText().trim();
        String l2 = jTextField3.getText().trim();
        String cnum = jTextField4.getText().trim();
        String city = jComboBox3.getSelectedItem().toString();

        if (cname.equals("Select Company")) {
            JOptionPane.showMessageDialog(this, "Please select a company!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (bname.isBlank()) {
            JOptionPane.showMessageDialog(this, "Branch Name field empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (bname.length() > 45) {
            JOptionPane.showMessageDialog(this, "Branch Name field out of range!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (l1.isBlank()) {
            JOptionPane.showMessageDialog(this, "Address Line 1 field empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (l1.length() > 45) {
            JOptionPane.showMessageDialog(this, "Address Line 1 field out of range!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (l2.isBlank()) {
            JOptionPane.showMessageDialog(this, "Address Line 2 field empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (l2.length() > 45) {
            JOptionPane.showMessageDialog(this, "Address Line 2 field out of range!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (cnum.isBlank()) {
            JOptionPane.showMessageDialog(this, "Contact Number field empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (cnum.length() > 45) {
            JOptionPane.showMessageDialog(this, "Contact Number field out of range!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (city.equals("Select City")) {
            JOptionPane.showMessageDialog(this, "Please select a city!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {

                if (clickedId != 0) {
                    if (clickedBname.equals(bname) && clickedCity.equals(city) && clickedCname.equals(cname) && clickedCnum.equals(cnum) && clickedL1.equals(l1) && clickedL2.equals(l2)) {

                    } else {
                        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Do you really want to update?", "Update", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (showConfirmDialog == JOptionPane.YES_OPTION) {
                            ResultSet rs1 = MySQL.search("SELECT * FROM `company` WHERE `name` = '" + cname + "'");
                            ResultSet rs2 = MySQL.search("SELECT * FROM `city` WHERE `name` = '" + city + "'");
                            rs1.next();
                            rs2.next();

                            MySQL.iud("UPDATE `branch` SET `company_id` = " + rs1.getInt("id") + ", `name` = '" + bname + "', `phone` = '" + cnum + "',`line1` = '" + l1 + "',`line2` = '" + l2 + "',`city_id` = " + rs2.getInt("id") + " WHERE `id` = " + clickedId + "");
                            JOptionPane.showMessageDialog(this, "Branch updated successfull!", "Success", JOptionPane.INFORMATION_MESSAGE);

                            clearFields();
                            loadTable();
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Please select a branch using table below!", "Warning", JOptionPane.WARNING_MESSAGE);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
        jLabel9.setForeground(new Color(230, 230, 230));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        jLabel9.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

        if (row != -1) {
            int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Do you really want to remove this selected Branch?", "Remove", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (showConfirmDialog == JOptionPane.YES_OPTION) {
                MySQL.iud("UPDATE `branch` SET `status` = 0 WHERE `id` = " + clickedId + "");
                clearFields();
                loadTable();
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Branch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Branch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Branch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Branch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Branch dialog = new Branch(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
